on:
 push:
   branches:
     - master



jobs:

 #build job
 build:

   # Name of the job
   name:  build
  
   # The  os to run the job on
   runs-on: ubuntu-latest

    # Steps 
   steps:
  
   - name: Checkout Code

     uses: actions/checkout@v2
    
   - name: Install node 16
    
     uses: actions/setup-node@v1

     with:
       node-version: 16.x


   - name: Install NPM Dependencies

     run: npm i
  
   - name: Build Project

     run: npm run build #./dist

   - name: Upload artifact in order to deploy
     
     uses: actions/upload-artifact@v2

     with:

       name: production-files

       path: ./build

        

 #deploy job

 deploy:

   name: deploy

   runs-on: ubuntu-latest

   needs: build

   steps:
     - name: Download artifact

       uses: actions/download-artifact@v3

       with:
         
         name: production-files

         path: ./build

     - name: Deploy to gh pages

       uses: peaceiris/actions-gh-pages@v3

       with:

         github_token: ${{secrets.DEPLOYMENTONGITHUBACCESSTOKEN}}

         publish_dir: ./build

        
         





 
